static const char *RcsId     = "$Header: /usr/local/CVS/DeviceServer/Generic/Motorisation/ControlBoxV2/src/GalilCoupledAxesClass.cpp,v 1.4 2011/07/15 09:47:43 buteau Exp $";
static const char *TagName   = "$Name: release_2_5_4 $";
static const char *HttpServer= "http://www.esrf.fr/computing/cs/tango/tango_doc/ds_doc/";
//+=============================================================================
//
// file :        GalilCoupledAxesClass.cpp
//
// description : C++ source for the GalilCoupledAxesClass. A singleton
//               class derived from DeviceClass. It implements the
//               command list and all properties and methods required
//               by the GalilCoupledAxes once per process.
//
// project :     TANGO Device Server
//
// $Author: buteau $
//
// $Revision: 1.4 $
//
// $Log: GalilCoupledAxesClass.cpp,v $
// Revision 1.4  2011/07/15 09:47:43  buteau
// MANTIS 19368
//
// Revision 1.3  2011/07/15 09:40:53  buteau
// MANTIS 19368
//
// Revision 1.2  2010/03/26 09:17:39  maven
// "Migration_Tango7_Part2"
//
// Revision 1.1  2007/11/16 09:39:31  leclercq
// no message
//
// Revision 1.1  2007/11/15 16:15:22  coquet
// added Coupled Axes support
// handeles internally coupled axes, device controls only the master position
// example : the detector table of swing with 2 synchronised motors
// the coupling is provided in the micro-code in the controlbox
//
//
// copyleft :   European Synchrotron Radiation Facility
//              BP 220, Grenoble 38043
//              FRANCE
//
//-=============================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================


#include <tango.h>

#include <GalilCoupledAxes.h>
#include <GalilCoupledAxesClass.h>


//+----------------------------------------------------------------------------
/**
 *	Create GalilCoupledAxesClass singleton and return it in a C function for Python usage
 */
//+----------------------------------------------------------------------------
extern "C" {
#ifdef WIN32

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_GalilCoupledAxes_class(const char *name) {
		return GalilCoupledAxes_ns::GalilCoupledAxesClass::init(name);
	}
}


namespace GalilCoupledAxes_ns
{
//+----------------------------------------------------------------------------
//
// method : 		BackwardCmd::execute()
// 
// description : 	method to trigger the execution of the command.
//                PLEASE DO NOT MODIFY this method core without pogo   
//
// in : - device : The device on which the command must be excuted
//		- in_any : The command input data
//
// returns : The command output data (packed in the Any object)
//
//-----------------------------------------------------------------------------
CORBA::Any *BackwardCmd::execute(Tango::DeviceImpl *device,const CORBA::Any &in_any)
{

	cout2 << "BackwardCmd::execute(): arrived" << endl;

	((static_cast<GalilCoupledAxes *>(device))->backward());
	return new CORBA::Any();
}

//+----------------------------------------------------------------------------
//
// method : 		ForwardClass::execute()
// 
// description : 	method to trigger the execution of the command.
//                PLEASE DO NOT MODIFY this method core without pogo   
//
// in : - device : The device on which the command must be excuted
//		- in_any : The command input data
//
// returns : The command output data (packed in the Any object)
//
//-----------------------------------------------------------------------------
CORBA::Any *ForwardClass::execute(Tango::DeviceImpl *device,const CORBA::Any &in_any)
{

	cout2 << "ForwardClass::execute(): arrived" << endl;

	((static_cast<GalilCoupledAxes *>(device))->forward());
	return new CORBA::Any();
}


//+----------------------------------------------------------------------------
//
// method : 		StopClass::execute()
// 
// description : 	method to trigger the execution of the command.
//                PLEASE DO NOT MODIFY this method core without pogo   
//
// in : - device : The device on which the command must be excuted
//		- in_any : The command input data
//
// returns : The command output data (packed in the Any object)
//
//-----------------------------------------------------------------------------
CORBA::Any *StopClass::execute(Tango::DeviceImpl *device,const CORBA::Any &in_any)
{

	cout2 << "StopClass::execute(): arrived" << endl;

	((static_cast<GalilCoupledAxes *>(device))->stop());
	return new CORBA::Any();
}


//
//----------------------------------------------------------------
//	Initialize pointer for singleton pattern
//----------------------------------------------------------------
//
GalilCoupledAxesClass *GalilCoupledAxesClass::_instance = NULL;

//+----------------------------------------------------------------------------
//
// method : 		GalilCoupledAxesClass::GalilCoupledAxesClass(string &s)
// 
// description : 	constructor for the GalilCoupledAxesClass
//
// in : - s : The class name
//
//-----------------------------------------------------------------------------
GalilCoupledAxesClass::GalilCoupledAxesClass(string &s):DeviceClass(s)
{

	cout2 << "Entering GalilCoupledAxesClass constructor" << endl;
	set_default_property();
	get_class_property();
	write_class_property();
	
	cout2 << "Leaving GalilCoupledAxesClass constructor" << endl;

}
//+----------------------------------------------------------------------------
//
// method : 		GalilCoupledAxesClass::~GalilCoupledAxesClass()
// 
// description : 	destructor for the GalilCoupledAxesClass
//
//-----------------------------------------------------------------------------
GalilCoupledAxesClass::~GalilCoupledAxesClass()
{
	_instance = NULL;
}

//+----------------------------------------------------------------------------
//
// method : 		GalilCoupledAxesClass::instance
// 
// description : 	Create the object if not already done. Otherwise, just
//			return a pointer to the object
//
// in : - name : The class name
//
//-----------------------------------------------------------------------------
GalilCoupledAxesClass *GalilCoupledAxesClass::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new GalilCoupledAxesClass(s);
		}
		catch (bad_alloc)
		{
			throw;
		}		
	}		
	return _instance;
}

GalilCoupledAxesClass *GalilCoupledAxesClass::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}

//+----------------------------------------------------------------------------
//
// method : 		GalilCoupledAxesClass::command_factory
// 
// description : 	Create the command object(s) and store them in the 
//			command list
//
//-----------------------------------------------------------------------------
void GalilCoupledAxesClass::command_factory()
{
	command_list.push_back(new StopClass("Stop",
		Tango::DEV_VOID, Tango::DEV_VOID,
		"",
		"",
		Tango::OPERATOR));
	command_list.push_back(new ForwardClass("Forward",
		Tango::DEV_VOID, Tango::DEV_VOID,
		"",
		"",
		Tango::OPERATOR));
	command_list.push_back(new BackwardCmd("Backward",
		Tango::DEV_VOID, Tango::DEV_VOID,
		"",
		"",
		Tango::OPERATOR));

	//	add polling if any
	for (unsigned int i=0 ; i<command_list.size(); i++)
	{
	}
}

//+----------------------------------------------------------------------------
//
// method : 		GalilCoupledAxesClass::get_class_property
// 
// description : 	Get the class property for specified name.
//
// in :		string	name : The property name
//
//+----------------------------------------------------------------------------
Tango::DbDatum GalilCoupledAxesClass::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}
//+----------------------------------------------------------------------------
//
// method : 		GalilCoupledAxesClass::get_default_device_property()
// 
// description : 	Return the default value for device property.
//
//-----------------------------------------------------------------------------
Tango::DbDatum GalilCoupledAxesClass::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//+----------------------------------------------------------------------------
//
// method : 		GalilCoupledAxesClass::get_default_class_property()
// 
// description : 	Return the default value for class property.
//
//-----------------------------------------------------------------------------
Tango::DbDatum GalilCoupledAxesClass::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}
//+----------------------------------------------------------------------------
//
// method : 		GalilCoupledAxesClass::device_factory
// 
// description : 	Create the device object(s) and store them in the 
//			device list
//
// in :		Tango::DevVarStringArray *devlist_ptr : The device name list
//
//-----------------------------------------------------------------------------
void GalilCoupledAxesClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{

	//	Create all devices.(Automatic code generation)
	//-------------------------------------------------------------
	for (unsigned long i=0 ; i < devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
						
		// Create devices and add it into the device list
		//----------------------------------------------------
		device_list.push_back(new GalilCoupledAxes(this, (*devlist_ptr)[i]));							 

		// Export device to the outside world
		// Check before if database used.
		//---------------------------------------------
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(device_list.back());
		else
			export_device(device_list.back(), (*devlist_ptr)[i]);
	}
	//	End of Automatic code generation
	//-------------------------------------------------------------

}
//+----------------------------------------------------------------------------
//	Method: GalilCoupledAxesClass::attribute_factory(vector<Tango::Attr *> &att_list)
//-----------------------------------------------------------------------------
void GalilCoupledAxesClass::attribute_factory(vector<Tango::Attr *> &att_list)
{
	//	Attribute : position
	positionAttrib	*position = new positionAttrib();
	Tango::UserDefaultAttrProp	position_prop;
	position_prop.set_label("position");
	position_prop.set_format("%6.3f");
	position_prop.set_description("position of the master axis");
	position->set_default_properties(position_prop);
	att_list.push_back(position);

	//	Attribute : forwardLimitSwitch
	forwardLimitSwitchAttrib	*forward_limit_switch = new forwardLimitSwitchAttrib();
	Tango::UserDefaultAttrProp	forward_limit_switch_prop;
	forward_limit_switch_prop.set_label("forward limit switch");
	forward_limit_switch_prop.set_description("state of the forward limit switch\ntrue if Forward LSW present");
	forward_limit_switch->set_default_properties(forward_limit_switch_prop);
	att_list.push_back(forward_limit_switch);

	//	Attribute : backwardLimitSwitch
	backwardLimitSwitchAttrib	*backward_limit_switch = new backwardLimitSwitchAttrib();
	Tango::UserDefaultAttrProp	backward_limit_switch_prop;
	backward_limit_switch_prop.set_label("backward limit switch");
	backward_limit_switch_prop.set_description("state of the backward limit switch\ntrue if Backward LSW present");
	backward_limit_switch->set_default_properties(backward_limit_switch_prop);
	att_list.push_back(backward_limit_switch);

	//	End of Automatic code generation
	//-------------------------------------------------------------
}

//+----------------------------------------------------------------------------
//
// method : 		GalilCoupledAxesClass::get_class_property()
// 
// description : 	Read the class properties from database.
//
//-----------------------------------------------------------------------------
void GalilCoupledAxesClass::get_class_property()
{
	//	Initialize your default values here (if not done with  POGO).
	//------------------------------------------------------------------

	//	Read class properties from database.(Automatic code generation)
	//------------------------------------------------------------------

	//	Call database and extract values
	//--------------------------------------------
	if (Tango::Util::instance()->_UseDb==true)
		get_db_class()->get_property(cl_prop);
	Tango::DbDatum	def_prop;
	int	i = -1;


	//	End of Automatic code generation
	//------------------------------------------------------------------

}

//+----------------------------------------------------------------------------
//
// method : 	GalilCoupledAxesClass::set_default_property
// 
// description: Set default property (class and device) for wizard.
//              For each property, add to wizard property name and description
//              If default value has been set, add it to wizard property and
//              store it in a DbDatum.
//
//-----------------------------------------------------------------------------
void GalilCoupledAxesClass::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;

	vector<string>	vect_data;
	//	Set Default Class Properties
	//	Set Default Device Properties
	prop_name = "Master";
	prop_desc = "letter of the master axis, from  A to H\nThis axis is the master axis\n";
	prop_def  = "";
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);

}
//+----------------------------------------------------------------------------
//
// method : 		GalilCoupledAxesClass::write_class_property
// 
// description : 	Set class description as property in database
//
//-----------------------------------------------------------------------------
void GalilCoupledAxesClass::write_class_property()
{
	//	First time, check if database used
	//--------------------------------------------
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("GalilCoupledAxes");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("This class is used to control coupled axes by controlling only the master axis.");
	str_desc.push_back("All the master-slave axis configuration are done by motorists in micro-code itself.");
	str_desc.push_back("Special commands if needed are accessed through MicrocodeDataViewer DS");
	str_desc.push_back("First need : a detector table with 2 motors");
	description << str_desc;
	data.push_back(description);
		
	//	put cvs location
	string	rcsId(RcsId);
	string	filename(classname);
	start = rcsId.find("/");
	if (start!=string::npos)
	{
		filename += "Class.cpp";
		end   = rcsId.find(filename);
		if (end>start)
		{
			string	strloc = rcsId.substr(start, end-start);
			//	Check if specific repository
			start = strloc.find("/cvsroot/");
			if (start!=string::npos && start>0)
			{
				string	repository = strloc.substr(0, start);
				if (repository.find("/segfs/")!=string::npos)
					strloc = "ESRF:" + strloc.substr(start, strloc.length()-start);
			}
			Tango::DbDatum	cvs_loc("cvs_location");
			cvs_loc << strloc;
			data.push_back(cvs_loc);
		}
	}

	//	Get CVS tag revision
	string	tagname(TagName);
	header = "$Name: ";
	start = header.length();
	string	endstr(" $");
	end   = tagname.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strtag = tagname.substr(start, end-start);
		Tango::DbDatum	cvs_tag("cvs_tag");
		cvs_tag << strtag;
		data.push_back(cvs_tag);
	}

	//	Get URL location
	string	httpServ(HttpServer);
	if (httpServ.length()>0)
	{
		Tango::DbDatum	db_doc_url("doc_url");
		db_doc_url << httpServ;
		data.push_back(db_doc_url);
	}

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("Device_4Impl");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	//--------------------------------------------
	get_db_class()->put_property(data);
}

}	// namespace
