/*----- PROTECTED REGION ID(CoilCorrectionStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        CoilCorrectionStateMachine.cpp
//
// description : C++ source for the «name» and its alowed
//               methods for commands and attributes
//
// project :     .
//
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// SVN only:
// $HeadURL:  $
//
// CVS only:
// $Source:  $
// $Log:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================



#include <CoilCorrection.h>
#include <CoilCorrectionClass.h>

/*----- PROTECTED REGION END -----*/


/*
 * CoilCorrection states description:
 *
 * ON :	Manual operation, each coil current could be manually set 
 * OFF :	All outputs are disabled 
 * RUNNING :	Automatic table lookup values applied 
 */

namespace CoilCorrection_ns
{

//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : CoilCorrection::is_Coil1ReadbackState_allowed()
 *	Description : Execution allowed for Coil1Readback attribute.
 */
//--------------------------------------------------------

bool CoilCorrection::is_Coil1Readback_allowed(Tango::AttReqType type)
{
		//	Not any excluded states for Coil1Readback attribute in READ access.
	
	/*----- PROTECTED REGION ID(CoilCorrection::read_Coil1ReadbackStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	CoilCorrection::read_Coil1ReadbackStateAllowed_READ

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : CoilCorrection::is_Coil2ReadbackState_allowed()
 *	Description : Execution allowed for Coil2Readback attribute.
 */
//--------------------------------------------------------

bool CoilCorrection::is_Coil2Readback_allowed(Tango::AttReqType type)
{
		//	Not any excluded states for Coil2Readback attribute in READ access.
	
	/*----- PROTECTED REGION ID(CoilCorrection::read_Coil2ReadbackStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	CoilCorrection::read_Coil2ReadbackStateAllowed_READ

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : CoilCorrection::is_Coil3ReadbackState_allowed()
 *	Description : Execution allowed for Coil3Readback attribute.
 */
//--------------------------------------------------------

bool CoilCorrection::is_Coil3Readback_allowed(Tango::AttReqType type)
{
		//	Not any excluded states for Coil3Readback attribute in READ access.
	
	/*----- PROTECTED REGION ID(CoilCorrection::read_Coil3ReadbackStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	CoilCorrection::read_Coil3ReadbackStateAllowed_READ

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : CoilCorrection::is_Coil4ReadbackState_allowed()
 *	Description : Execution allowed for Coil4Readback attribute.
 */
//--------------------------------------------------------

bool CoilCorrection::is_Coil4Readback_allowed(Tango::AttReqType type)
{
		//	Not any excluded states for Coil4Readback attribute in READ access.
	
	/*----- PROTECTED REGION ID(CoilCorrection::read_Coil4ReadbackStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	CoilCorrection::read_Coil4ReadbackStateAllowed_READ

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : CoilCorrection::is_Coil1SetpointState_allowed()
 *	Description : Execution allowed for Coil1Setpoint attribute.
 */
//--------------------------------------------------------

bool CoilCorrection::is_Coil1Setpoint_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
			//	Not any excluded states for Coil1Setpoint attribute in WRITE access.
		
	/*----- PROTECTED REGION ID(CoilCorrection::Coil1SetpointStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	CoilCorrection::Coil1SetpointStateAllowed_WRITE

		return true;
	}
	else
		//	Not any excluded states for Coil1Setpoint attribute in READ access.
	
	/*----- PROTECTED REGION ID(CoilCorrection::read_Coil1SetpointStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	CoilCorrection::read_Coil1SetpointStateAllowed_READ

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : CoilCorrection::is_Coil2SetpointState_allowed()
 *	Description : Execution allowed for Coil2Setpoint attribute.
 */
//--------------------------------------------------------

bool CoilCorrection::is_Coil2Setpoint_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
			//	Not any excluded states for Coil2Setpoint attribute in WRITE access.
		
	/*----- PROTECTED REGION ID(CoilCorrection::Coil2SetpointStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	CoilCorrection::Coil2SetpointStateAllowed_WRITE

		return true;
	}
	else
		//	Not any excluded states for Coil2Setpoint attribute in READ access.
	
	/*----- PROTECTED REGION ID(CoilCorrection::read_Coil2SetpointStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	CoilCorrection::read_Coil2SetpointStateAllowed_READ

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : CoilCorrection::is_Coil3SetpointState_allowed()
 *	Description : Execution allowed for Coil3Setpoint attribute.
 */
//--------------------------------------------------------

bool CoilCorrection::is_Coil3Setpoint_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
			//	Not any excluded states for Coil3Setpoint attribute in WRITE access.
		
	/*----- PROTECTED REGION ID(CoilCorrection::Coil3SetpointStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	CoilCorrection::Coil3SetpointStateAllowed_WRITE

		return true;
	}
	else
		//	Not any excluded states for Coil3Setpoint attribute in READ access.
	
	/*----- PROTECTED REGION ID(CoilCorrection::read_Coil3SetpointStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	CoilCorrection::read_Coil3SetpointStateAllowed_READ

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : CoilCorrection::is_Coil4SetpointState_allowed()
 *	Description : Execution allowed for Coil4Setpoint attribute.
 */
//--------------------------------------------------------

bool CoilCorrection::is_Coil4Setpoint_allowed(Tango::AttReqType type)
{
	//	Check if access type.
	if ( type!=Tango::READ_REQ )
	{
			//	Not any excluded states for Coil4Setpoint attribute in WRITE access.
		
	/*----- PROTECTED REGION ID(CoilCorrection::Coil4SetpointStateAllowed_WRITE) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	CoilCorrection::Coil4SetpointStateAllowed_WRITE

		return true;
	}
	else
		//	Not any excluded states for Coil4Setpoint attribute in READ access.
	
	/*----- PROTECTED REGION ID(CoilCorrection::read_Coil4SetpointStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	CoilCorrection::read_Coil4SetpointStateAllowed_READ

	return true;
}


	/*----- PROTECTED REGION ID(CoilCorrection::are_dynamic_attributes_allowed) ENABLED START -----*/

	//	Add your code to check if dynamic attributes are alowed

	/*----- PROTECTED REGION END -----*/	//	CoilCorrection::are_dynamic_attributes_allowed


//=================================================
//		Commands Allowed Methods
//=================================================


//--------------------------------------------------------
/**
 *	Method      : CoilCorrection::is_OnState_allowed()
 *	Description : Execution allowed for On command.
 */
//--------------------------------------------------------

bool CoilCorrection::is_On_allowed(const CORBA::Any &any)
{
	if (	//	Compare device state with not allowed states for command 
		get_state() == Tango::ON)
	{

	/*----- PROTECTED REGION ID(CoilCorrection::OnStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	CoilCorrection::OnStateAllowed

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : CoilCorrection::is_OffState_allowed()
 *	Description : Execution allowed for Off command.
 */
//--------------------------------------------------------

bool CoilCorrection::is_Off_allowed(const CORBA::Any &any)
{
	if (	//	Compare device state with not allowed states for command 
		get_state() == Tango::OFF)
	{

	/*----- PROTECTED REGION ID(CoilCorrection::OffStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	CoilCorrection::OffStateAllowed

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : CoilCorrection::is_LoadState_allowed()
 *	Description : Execution allowed for Load command.
 */
//--------------------------------------------------------

bool CoilCorrection::is_Load_allowed(const CORBA::Any &any)
{
	if (	//	Compare device state with not allowed states for command 
		get_state() == Tango::RUNNING)
	{

	/*----- PROTECTED REGION ID(CoilCorrection::LoadStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	CoilCorrection::LoadStateAllowed

		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : CoilCorrection::is_RunState_allowed()
 *	Description : Execution allowed for Run command.
 */
//--------------------------------------------------------

bool CoilCorrection::is_Run_allowed(const CORBA::Any &any)
{
	if (	//	Compare device state with not allowed states for command 
		get_state() == Tango::RUNNING)
	{

	/*----- PROTECTED REGION ID(CoilCorrection::RunStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	CoilCorrection::RunStateAllowed

		return false;
	}
	return true;
}


	/*----- PROTECTED REGION ID(CoilCorrection::are_dynamic_commands_allowed) ENABLED START -----*/

	//	Add your code to check if dynamic commands are alowed

	/*----- PROTECTED REGION END -----*/	//	CoilCorrection::are_dynamic_commands_allowed

}	// namespace CoilCorrection_ns
